name: Deploy to AWS EC2 using Docker Compose

on:
  push:
    branches:
      - main # or the branch you want to deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker buildx build --push --tag ${{ secrets.DOCKERHUB_USERNAME }}/guidel_medregch_backend-backend:latest ./backend
          docker buildx build --push --tag ${{ secrets.DOCKERHUB_USERNAME }}/guidel_medregch_backend-frontend:latest ./frontend
